INSERT INTO STUDENT VALUES(1, "Anurag", 20);
INSERT INTO STUDENT VALUES(2, "Aman", 21);
INSERT INTO STUDENT VALUES(3, "Amit", 22);

-- Output

INSERT INTO STUDENT VALUES(1, "Anurag", 20);
INSERT INTO STUDENT VALUES(2, "Aman", 21);
INSERT INTO STUDENT VALUES(3, "Amit", 22);